/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#23005c",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#b4c5ff",
        "on-error-container": "#93000a",
        "surface-tint": "#0053db",
        "background": "#f7f9fb",
        "tertiary-fixed": "#e9ddff",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191c1e",
        "on-secondary": "#ffffff",
        "secondary": "#006c49",
        "surface-container-highest": "#e0e3e5",
        "on-secondary-container": "#00714d",
        "secondary-fixed-dim": "#4edea3",
        "surface-dim": "#d8dadc",
        "inverse-surface": "#2d3133",
        "outline": "#737686",
        "primary": "#2563eb",
        "on-tertiary": "#ffffff",
        "tertiary": "#632ecd",
        "on-tertiary-container": "#f6edff",
        "inverse-primary": "#b4c5ff",
        "on-background": "#191c1e",
        "surface-container": "#eceef0",
        "surface-container-high": "#e6e8ea",
        "outline-variant": "#c3c6d7",
        "primary-container": "#2563eb",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#002113",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#005236",
        "on-primary-fixed-variant": "#003ea8",
        "on-tertiary-fixed-variant": "#5516be",
        "surface-variant": "#e0e3e5",
        "secondary-container": "#6cf8bb",
        "surface-container-low": "#f2f4f6",
        "error": "#ba1a1a",
        "on-primary-container": "#eeefff",
        "on-primary-fixed": "#00174b",
        "surface-bright": "#f7f9fb",
        "tertiary-container": "#7d4ce7",
        "surface": "#f7f9fb",
        "secondary-fixed": "#6ffbbe",
        "on-primary": "#ffffff",
        "on-surface-variant": "#434655",
        "inverse-on-surface": "#eff1f3",
        "tertiary-fixed-dim": "#d0bcff",
        "coral": "#ff6b6b",
        "amber": "#f59e0b",
        "cyan": "#06b6d4",
        "pink": "#ec4899",
        "lime": "#84cc16",
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
